config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users

  resources :blogs do
    resources :posts, only: [ :create, :destroy ]
  end

  match '/users/:id', to: 'users#make_admin' , via: 'post'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'blogs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :posts, dependent: :destroy

  validates :title, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :blog

  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: true

  validates :name, presence: true

  has_one :blog, dependent: :destroy

  before_save { self.email = email.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :name ])
    devise_parameter_sanitizer.permit(:account_update, keys: [ :name ])
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blog=Blog.find(params[:id])
    @posts = @blog.posts
    @post = Post.new
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
    @blog=Blog.find(params[:id])
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
    if @blog.save
      redirect_to @blog
    else
      render :new
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    @blog=Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to @blog
    else
      render :edit
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog=Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :description, :user_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :destroy]

  # GET /posts/new
  def new
    @post = Post.new
  end

  # POST /posts
  # POST /posts.json
  def create
    @blog=Blog.find(params[:blog_id])
    @post=@blog.posts.build(post_params)
    @post.save
    redirect_to blog_path(@blog)
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @blog=Blog.find(params[:blog_id])
    @post=@blog.posts.find(params[:id])
    @post.destroy
    redirect_to blog_path(@blog)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:body, :blog_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def make_admin
    @user=User.find(params[:id])
    @user.toggle!(:admin)
    redirect_to users_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :admin, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %><br>
    <%= form.text_field :title, id: :blog_title %>
  </div>

  <div class="field">
    <%= form.label :description %><br>
    <%= form.text_area :description, id: :blog_description, rows: 2 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<div class="shared-links">
  <%= link_to 'Show', @blog %> |
  <%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table class="table table-striped table-dark">
  <thead class="thead-dark">
    <tr class="table-dark">
      <th scope="col">Blog title</th>
      <th scope="col">Author</th>
      <th scope="col">Posts</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr class="table-dark">
        <td><%= blog.title %></td>
        <td><%= blog.user.name %></td>
        <td><%= blog.posts.count %></td>
        <td><%= link_to 'Show', blog_path(blog) %></td>
        <% if current_user && current_user.admin? && !blog.user.admin? %>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <% end %>
        <% if current_user && current_user.admin? && !blog.user.admin? %>
        <td><%= link_to 'Delete', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<div class="shared-links">
  <%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<div class="main-info">
  <p class="p-right">
    <strong>Author:</strong>
    <%= @blog.user.name %>
  </p>

  <p class="p-right">
    <strong>Title:</strong>
    <%= @blog.title %>
  </p>

  <p class="p-right">
    <strong>Description:</strong>
    <% if @blog.description.nil? %>
      no description
    <% else %>
      <%= @blog.description %>
    <% end %>
  </p>

  <br>

  <% if current_user==@blog.user %>
    <p><strong>Add a post:</strong></p>
      <%= render 'posts/form' %>
  <% end %>

  <br>

  <p><strong>Posts:</strong></p>
    <% if @posts.empty? %>
      <p>no posts</p>
    <% else %>
      <% @posts.each do |post| %>
        <div class="card text-center" style="border: 1px solid black; margin-bottom: 5px;">
          <div class="card-body">
            <div class="card-text"><%= post.body %></div>
            <% if (current_user && current_user.admin? && !@blog.user.admin?) || current_user == @blog.user %>
               <%= link_to 'Delete post', [@blog, post], method: :delete, data: { confirm: 'Are you sure?' }, class:"card-link" %>
             <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
</div>

<br>

<div class="shared-links">
  <% if (current_user && current_user.admin? && !@blog.user.admin?) || current_user == @blog.user %>
    <%= link_to 'Edit blog', edit_blog_path(@blog) %> |
    <%= link_to 'Delete blog', @blog, method: :delete, data: { confirm: 'Are you sure?' } %> |
  <% end %>
  <%= link_to 'Back', blogs_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark">
      <% if current_user %>
        <ul class="nav navbar-nav navbar-left">
          <li><span class="navbar-brand mb-0">Hello, <%= current_user.name %></span></li>
          <li><%= link_to "Log out", destroy_user_session_url, method: :delete, class:"navbar-brand" %></li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-left">
          <li><%= link_to "Sign in", new_user_session_url, class:"navbar-brand" %></li>
          <li><span class="navbar-brand mb-0">or</span></li>
          <li><%= link_to "Sign up", new_user_registration_url, class:"navbar-brand" %></li>
        </ul>
      <% end %>
    </nav>

    <nav class="navbar navbar-dark bg-dark">
      <% if current_user %>
        <ul class="nav navbar-nav navbar-left">
          <li><%= link_to 'All blogs', blogs_path, class:"navbar-brand" %></li>
          <li><%= link_to 'Profile', user_path(current_user), class:"navbar-brand" %></li>
          <li><% if current_user.blog.nil? %>
            <%= link_to 'Create blog', new_blog_path, class:"navbar-brand" %>
          <% else %>
            <%= link_to 'My blog', blog_path(current_user.blog), class:"navbar-brand" %>
          <% end %></li>
          <% if current_user.admin? %>
            <li><%= link_to 'All users', users_path, class:"navbar-brand" %></li>
          <% end %>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-left">
          <li><%= link_to 'All blogs', blogs_path, class:"navbar-brand" %></li>
        </ul>
      <% end %>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: [ @blog, @post ], local: true) do |form| %>
  <div class="field">
    <%= form.text_field :body, id: :post_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %><br>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %><br>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :password %><br>
    <%= form.password_field :password, id: :user_password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %><br>
    <%= form.password_field :password_confirmation, id: :user_password_confirmation %>
  </div>

  <% if current_user && current_user.admin? && !@user.admin? %>
    <p><%= link_to 'Make admin', @user, method: :make_admin %></p>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<div class="shared-links">
  <%= link_to 'Show', @user %> |
  <%= link_to 'Back', @user %>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table table-striped table-dark">
  <thead class="thead-dark">
    <tr class="table-dark">
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Role</th>
      <th scope="col">Blog</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr  class="table-dark">
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><% if user.admin? %>
              Admin
            <% else %>
              User
            <% end %>
        </td>
        <td><% if user.blog.nil? %>
              no blog
            <% else %>
              <%= link_to user.blog.title, blog_path(user.blog) %>
            <% end %>
        </td>
        <td><%= link_to 'Show', user %></td>
        <% if current_user && current_user.admin? && !user.admin? %>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <% end %>
        <% if current_user && current_user.admin? && !user.admin? %>
          <td><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<div class="shared-links">
  <%= link_to 'Back', blogs_path %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class="main-info">
  <p class="p-right">
    <strong>Name:</strong>
    <%= @user.name %>
  </p>

  <p class="p-right">
    <strong>Email:</strong>
    <%= @user.email %>
  </p>

  <p class="p-right">
    <strong>Role:</strong>
    <% if @user.admin? %>
      Admin
    <% else %>
      User
    <% end %>
  </p>

  <% if !@user.blog.nil? %>
    <p><%= link_to 'Show blog',  blog_path(@user.blog) %></p>
  <% end %>

  <% if current_user && current_user.admin? && !@user.admin? %>
    <p><%= link_to 'Make admin', @user, method: :make_admin %></p>
  <% end %>
</div>

<br>

<div class="shared-links">
  <% if (current_user && current_user.admin? && !@user.admin?) || current_user == @user %>
    <%= link_to 'Edit', edit_user_path(@user) %> |
    <%= link_to 'Delete', @user, method: :delete, data: { confirm: 'Are you sure?' } %> |
  <% end %>
  <%= link_to 'Back', blogs_path %>
</div>